# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'apbs_groupBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_apbs_GroupBox(object):
    def setupUi(self, apbs_GroupBox):
        apbs_GroupBox.setObjectName("apbs_GroupBox")
        apbs_GroupBox.resize(480, 640)
        self.gridLayout = QtWidgets.QGridLayout(apbs_GroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.apbs_options_button = QtWidgets.QToolButton(apbs_GroupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.apbs_options_button.setFont(font)
        self.apbs_options_button.setObjectName("apbs_options_button")
        self.gridLayout_3.addWidget(self.apbs_options_button, 0, 2, 1, 1, QtCore.Qt.AlignVCenter)
        self.label_6 = QtWidgets.QLabel(apbs_GroupBox)
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.apbs_focus_lineEdit = QtWidgets.QLineEdit(apbs_GroupBox)
        self.apbs_focus_lineEdit.setObjectName("apbs_focus_lineEdit")
        self.gridLayout_3.addWidget(self.apbs_focus_lineEdit, 1, 1, 1, 2, QtCore.Qt.AlignVCenter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.apbs_calculate_checkBox = QtWidgets.QCheckBox(apbs_GroupBox)
        self.apbs_calculate_checkBox.setCheckable(True)
        self.apbs_calculate_checkBox.setChecked(True)
        self.apbs_calculate_checkBox.setObjectName("apbs_calculate_checkBox")
        self.gridLayout_3.addWidget(self.apbs_calculate_checkBox, 0, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.label_5 = QtWidgets.QLabel(apbs_GroupBox)
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.label_7 = QtWidgets.QLabel(apbs_GroupBox)
        self.label_7.setTextFormat(QtCore.Qt.PlainText)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.apbs_outputmap_lineEdit = QtWidgets.QLineEdit(apbs_GroupBox)
        self.apbs_outputmap_lineEdit.setObjectName("apbs_outputmap_lineEdit")
        self.gridLayout_3.addWidget(self.apbs_outputmap_lineEdit, 3, 1, 1, 2, QtCore.Qt.AlignVCenter)
        self.apbs_grid_options_button = QtWidgets.QToolButton(apbs_GroupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.apbs_grid_options_button.setFont(font)
        self.apbs_grid_options_button.setObjectName("apbs_grid_options_button")
        self.gridLayout_3.addWidget(self.apbs_grid_options_button, 2, 2, 1, 1, QtCore.Qt.AlignVCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 4, 0, 1, 1)
        self.apbs_finegrid_spinBox = QtWidgets.QSpinBox(apbs_GroupBox)
        self.apbs_finegrid_spinBox.setSingleStep(1)
        self.apbs_finegrid_spinBox.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.apbs_finegrid_spinBox.setObjectName("apbs_finegrid_spinBox")
        self.gridLayout_3.addWidget(self.apbs_finegrid_spinBox, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.retranslateUi(apbs_GroupBox)
        QtCore.QMetaObject.connectSlotsByName(apbs_GroupBox)

    def retranslateUi(self, apbs_GroupBox):
        _translate = QtCore.QCoreApplication.translate
        apbs_GroupBox.setWindowTitle(_translate("apbs_GroupBox", "GroupBox"))
        self.apbs_options_button.setText(_translate("apbs_GroupBox", "Options..."))
        self.label_6.setText(_translate("apbs_GroupBox", "Focus Selection (optional):"))
        self.apbs_calculate_checkBox.setText(_translate("apbs_GroupBox", "Calculate Map with APBS"))
        self.label_5.setText(_translate("apbs_GroupBox", "Grid Spacing (A):"))
        self.label_7.setText(_translate("apbs_GroupBox", "Output Map Object:"))
        self.apbs_grid_options_button.setText(_translate("apbs_GroupBox", "Options..."))
