# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pdb2pqr_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pdb2pqr_widget(object):
    def setupUi(self, pdb2pqr_widget):
        pdb2pqr_widget.setObjectName("pdb2pqr_widget")
        pdb2pqr_widget.resize(396, 248)
        self.gridLayout_2 = QtWidgets.QGridLayout(pdb2pqr_widget)
        self.gridLayout_2.setContentsMargins(12, -1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(pdb2pqr_widget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1, QtCore.Qt.AlignVCenter)
        self.label_2 = QtWidgets.QLabel(pdb2pqr_widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.label = QtWidgets.QLabel(pdb2pqr_widget)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.checkBox = QtWidgets.QCheckBox(pdb2pqr_widget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 2, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(pdb2pqr_widget)
        QtCore.QMetaObject.connectSlotsByName(pdb2pqr_widget)

    def retranslateUi(self, pdb2pqr_widget):
        _translate = QtCore.QCoreApplication.translate
        pdb2pqr_widget.setWindowTitle(_translate("pdb2pqr_widget", "Form"))
        self.label_2.setText(_translate("pdb2pqr_widget", "Command line flags:"))
        self.label.setText(_translate("pdb2pqr_widget", "pdb2pqr adds hydrogens and missing sidechain atoms and assigns partial charges and radii.\n"
"It removes ligands and modified residues."))
        self.checkBox.setText(_translate("pdb2pqr_widget", "Ignore warnings"))
