# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plugin_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_plugin_dialog(object):
    def setupUi(self, plugin_dialog):
        plugin_dialog.setObjectName("plugin_dialog")
        plugin_dialog.resize(480, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(plugin_dialog.sizePolicy().hasHeightForWidth())
        plugin_dialog.setSizePolicy(sizePolicy)
        plugin_dialog.setMinimumSize(QtCore.QSize(300, 400))
        self.gridLayout_2 = QtWidgets.QGridLayout(plugin_dialog)
        self.gridLayout_2.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.run_button = QtWidgets.QPushButton(plugin_dialog)
        self.run_button.setObjectName("run_button")
        self.gridLayout.addWidget(self.run_button, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(plugin_dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        self.about_button = QtWidgets.QToolButton(plugin_dialog)
        self.about_button.setObjectName("about_button")
        self.gridLayout.addWidget(self.about_button, 0, 2, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.tabWidget = QtWidgets.QTabWidget(plugin_dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_main = MainWidget()
        self.tab_main.setObjectName("tab_main")
        self.tabWidget.addTab(self.tab_main, "")
        self.tab_template = QtWidgets.QWidget()
        self.tab_template.setObjectName("tab_template")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_template)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.tab_template)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.template_textEdit = QtWidgets.QTextEdit(self.tab_template)
        self.template_textEdit.setObjectName("template_textEdit")
        self.verticalLayout.addWidget(self.template_textEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_template, "")
        self.tab_paths = QtWidgets.QWidget()
        self.tab_paths.setObjectName("tab_paths")
        self.tabWidget.addTab(self.tab_paths, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(plugin_dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(plugin_dialog)

    def retranslateUi(self, plugin_dialog):
        _translate = QtCore.QCoreApplication.translate
        plugin_dialog.setWindowTitle(_translate("plugin_dialog", "Dialog"))
        self.run_button.setText(_translate("plugin_dialog", "Run"))
        self.label_2.setText(_translate("plugin_dialog", "APBS Tools plugin"))
        self.about_button.setText(_translate("plugin_dialog", "About..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_main), _translate("plugin_dialog", "Main"))
        self.label.setText(_translate("plugin_dialog", "This is the template for the input file to APBS. Variable names in curly braces are replaced by their corresponding values."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_template), _translate("plugin_dialog", "APBS Template"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_paths), _translate("plugin_dialog", "Paths"))
from mainwidget import MainWidget
