# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pqr_pymol_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pqr_pymol_widget(object):
    def setupUi(self, pqr_pymol_widget):
        pqr_pymol_widget.setObjectName("pqr_pymol_widget")
        pqr_pymol_widget.resize(370, 272)
        self.gridLayout_2 = QtWidgets.QGridLayout(pqr_pymol_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(pqr_pymol_widget)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(pqr_pymol_widget)
        QtCore.QMetaObject.connectSlotsByName(pqr_pymol_widget)

    def retranslateUi(self, pqr_pymol_widget):
        _translate = QtCore.QCoreApplication.translate
        pqr_pymol_widget.setWindowTitle(_translate("pqr_pymol_widget", "Form"))
        self.label.setText(_translate("pqr_pymol_widget", "PyMOL can directly generate PQR files using standard protein residues and AMBER charges."))
