# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viz_groupBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_viz_GroupBox(object):
    def setupUi(self, viz_GroupBox):
        viz_GroupBox.setObjectName("viz_GroupBox")
        viz_GroupBox.resize(419, 640)
        self.gridLayout = QtWidgets.QGridLayout(viz_GroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.other_viz_checkBox = QtWidgets.QCheckBox(viz_GroupBox)
        self.other_viz_checkBox.setObjectName("other_viz_checkBox")
        self.gridLayout_5.addWidget(self.other_viz_checkBox, 6, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(viz_GroupBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_10.setFont(font)
        self.label_10.setTextFormat(QtCore.Qt.RichText)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 3, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 2)
        self.viz_method_comboBox = QtWidgets.QComboBox(viz_GroupBox)
        self.viz_method_comboBox.setObjectName("viz_method_comboBox")
        self.gridLayout_5.addWidget(self.viz_method_comboBox, 5, 0, 1, 3, QtCore.Qt.AlignVCenter)
        self.viz_surface_checkBox = QtWidgets.QCheckBox(viz_GroupBox)
        self.viz_surface_checkBox.setChecked(True)
        self.viz_surface_checkBox.setObjectName("viz_surface_checkBox")
        self.gridLayout_5.addWidget(self.viz_surface_checkBox, 0, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.label_9 = QtWidgets.QLabel(viz_GroupBox)
        self.label_9.setTextFormat(QtCore.Qt.PlainText)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 3, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.other_viz_options_button = QtWidgets.QToolButton(viz_GroupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.other_viz_options_button.setFont(font)
        self.other_viz_options_button.setObjectName("other_viz_options_button")
        self.gridLayout_5.addWidget(self.other_viz_options_button, 6, 2, 1, 1)
        self.viz_map_comboBox = QtWidgets.QComboBox(viz_GroupBox)
        self.viz_map_comboBox.setEditable(True)
        self.viz_map_comboBox.setObjectName("viz_map_comboBox")
        self.gridLayout_5.addWidget(self.viz_map_comboBox, 2, 1, 1, 2, QtCore.Qt.AlignVCenter)
        self.viz_range_spinBox = QtWidgets.QDoubleSpinBox(viz_GroupBox)
        self.viz_range_spinBox.setObjectName("viz_range_spinBox")
        self.gridLayout_5.addWidget(self.viz_range_spinBox, 3, 1, 1, 1, QtCore.Qt.AlignVCenter)
        self.label_2 = QtWidgets.QLabel(viz_GroupBox)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 2, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 6, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(viz_GroupBox)
        self.label_8.setTextFormat(QtCore.Qt.PlainText)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 4, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.viz_ramp_lineEdit = QtWidgets.QLineEdit(viz_GroupBox)
        self.viz_ramp_lineEdit.setObjectName("viz_ramp_lineEdit")
        self.gridLayout_5.addWidget(self.viz_ramp_lineEdit, 4, 1, 1, 2, QtCore.Qt.AlignVCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 7, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 0, 0, 1, 1)

        self.retranslateUi(viz_GroupBox)
        QtCore.QMetaObject.connectSlotsByName(viz_GroupBox)

    def retranslateUi(self, viz_GroupBox):
        _translate = QtCore.QCoreApplication.translate
        viz_GroupBox.setWindowTitle(_translate("viz_GroupBox", "GroupBox"))
        self.other_viz_checkBox.setText(_translate("viz_GroupBox", "Other Visualizations"))
        self.label_10.setText(_translate("viz_GroupBox", "Projects the electrostatic potential onto the molecular surface"))
        self.viz_surface_checkBox.setText(_translate("viz_GroupBox", "Molecular Surface Visualization"))
        self.label_9.setText(_translate("viz_GroupBox", "Range: +/-"))
        self.other_viz_options_button.setText(_translate("viz_GroupBox", "Options..."))
        self.label_2.setText(_translate("viz_GroupBox", "Map:"))
        self.label_8.setText(_translate("viz_GroupBox", "Output Ramp:"))
